### ISSUE TITLE
Packaging tips

### ISSUE THREAD

**Issue by rgrinberg** [lebotlan/ocaml-cryptodbm#1]
Hi!

It looks like you've chosen to use jbuilder as your build system. Good choice! Here are some tips for more standard packaging using jbuilder/opam:

* There's no need to .install files.
* This directory isn't necessary here https://github.com/lebotlan/ocaml-cryptodbm/tree/master/cryptodbm.0.84.1
* Same for this https://github.com/lebotlan/ocaml-cryptodbm/tree/master/opam-releases/cryptodbm.0.84.1
* Create a cryptodbm.descr file from https://github.com/lebotlan/ocaml-cryptodbm/blob/master/opam-releases/cryptodbm.0.84.1/descr in your repo's root. If you use opam publish, it will fetch the description from here.

**Comment by lebotlan** [comment]
All fixed. Thank you for these suggestions!
